"""LLM-as-judge detector — uses kimi to evaluate AI likelihood per segment."""

import json
import logging
import re

from app.core.llm import chat

logger = logging.getLogger(__name__)

JUDGE_SYSTEM_PROMPT = """You are an expert AI text detection system. Your job is to evaluate whether a piece of text was written by a human or generated by an AI language model.

Analyze the text for these signals:
1. BURSTINESS: Human text has wildly varying sentence lengths. AI text is uniform.
2. VOCABULARY: AI overuses words like "delve", "crucial", "moreover", "comprehensive", "facilitate", "robust", "seamless", "paradigm", "holistic", "leverage".
3. STRUCTURE: AI writes formulaic paragraphs of similar length. Humans vary paragraph structure.
4. SENTENCE STARTERS: AI repeats starters like "Additionally", "Furthermore", "Moreover", "However". Humans vary more.
5. TONE: AI sounds polished and impersonal. Humans use contractions, hedging, first-person voice, and informal touches.
6. PERPLEXITY: AI text is predictable — each word follows logically from the last. Human text has more surprising word choices.

You MUST respond with ONLY a valid JSON object in this exact format:
{"score": <integer 0-100>, "reasoning": "<brief 1-2 sentence explanation>"}

Where score 0 = definitely human, 100 = definitely AI.
Do not include any text outside the JSON object."""


def judge(text: str, model: str | None = None) -> dict:
    """Score text using LLM as judge.

    Returns:
        dict with 'score' (0-100) and 'reasoning' string.
        On failure, returns score=50 (neutral) with error reasoning.
    """
    try:
        response = chat(
            messages=[
                {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                {"role": "user", "content": f"Evaluate this text:\n\n{text}"},
            ],
            model=model,
            temperature=0.1,
            seed=42,
        )

        # Parse JSON from response — handle potential markdown wrapping
        cleaned = response.strip()
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
            cleaned = re.sub(r"\s*```$", "", cleaned)

        result = json.loads(cleaned)
        score = max(0, min(100, int(result.get("score", 50))))
        reasoning = result.get("reasoning", "")

        return {"score": score, "reasoning": reasoning}

    except Exception as e:
        logger.warning("LLM judge failed: %s — returning neutral score", e)
        return {"score": 50, "reasoning": f"Judge unavailable: {e}"}


def judge_segments(segments: list[str], model: str | None = None) -> list[dict]:
    """Score multiple text segments. Returns list of judge results."""
    return [judge(seg, model=model) for seg in segments]
